upload_dir: "uploads"
nmparse_url: "https://api.ideaconsult.net/gracious/enm/gracious/nmparser"
SOLR_ROOT: "https://solr-kc.ideaconsult.net/solr/"
SOLR_VECTOR: "spectrum_p1024"
SOLR_COLLECTION: "charisma_protected"
